# Example Code generated by Beijing Volcanoengine Technology.
from __future__ import print_function
import volcenginesdkcore
import volcenginesdktranslate20250301
from volcenginesdkcore.rest import ApiException

if __name__ == '__main__':
    # 注意示例代码安全，代码泄漏会导致AK/SK泄漏，有极大的安全风险。
    configuration = volcenginesdkcore.Configuration()
    configuration.ak = "AKLTODc1YTIzYjg0MmIxNDc1NTljZTJiYWZjNGIyYjM0ZjM"
    configuration.sk = "TlRrek1UZzJZV0kzT1dGaU5HRXpOemxoTldKbVpURXpNemhtT1RWa09XTQ=="
    configuration.region = "cn-beijing"
    # set default configuration
    volcenginesdkcore.Configuration.set_default(configuration)

    # use global default configuration
    api_instance = volcenginesdktranslate20250301.TRANSLATE20250301Api()
    # Create a proper TranslateTextRequest with required parameters
    translate_text_request = volcenginesdktranslate20250301.TranslateTextRequest(
        target_language="en",  # Translate to English
        source_language="zh",  # Translate from Chinese
        text_list=["你好，世界"]  # Text to translate
    )
    
    try:
        # 复制代码运行示例，请自行打印API返回值。
        response = api_instance.translate_text(translate_text_request)
        print("Translation response:", response)
    except ApiException as e:
        # 复制代码运行示例，请自行打印API错误信息。
        print("Exception when calling api: %s\n" % e)
        pass